name: Docker Build & Trivy Scan

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  docker-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t hello-flask:${{ github.sha }} .

      - name: Run Trivy scan (Table Report)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: hello-flask:${{ github.sha }}
          format: table
          output: trivy-report.txt
          exit-code: 0
          ignore-unfixed: true

      - name: Generate SARIF Report
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: hello-flask:${{ github.sha }}
          format: sarif
          output: trivy-report.sarif
          exit-code: 0
          ignore-unfixed: true

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-report.sarif

      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports-${{ github.run_number }}
          path: |
            trivy-report.txt
            trivy-report.sarif
          retention-days: 30
